### ISSUE TITLE
Wrong /albuminfo results with tracks that aren't even tracks

### ISSUE THREAD

**Issue by raitonoberu** [raitonoberu/harmonoid-service#12]
https://github.com/alexmercerind/harmonoid/issues/35

Hi, @alexmercerind&@mytja !
I did a little research to find out the cause of the bug.

http://harmonoid-ru.herokuapp.com/albuminfo?album_id=MPREb_9gAdrkio5lF
When we try to get tracks of the album, the first track is:
```json
{
    "track_id": "LRq3xHN2s_c",
    "track_name": "!!!!!!!",
    "track_artists": [
        "Billie Eilish"
    ],
    "track_number": 1,
    "track_duration": 14000
}
```
But if we try to open it in the browser (https://music.youtube.com/watch?v=LRq3xHN2s_c), returns a different track. So, track_id is wrong.

Now remember that we get each individual track_id by searching for each individual track. When we try to search for "Billie Eilish - !!!!!!!" (http://harmonoid-ru.herokuapp.com/search?keyword=billy%20eilish%20-%20%21%21%21%21%21%21%21&mode=track), the first result is "Billie Eilish - my future". That's the problem.

Any ideas?

**Comment by alexmercerind** [comment]
Oh great!
Absolutely, you did a really great research over this. Yeah, searching for those tracks individually is the problem. It picks the wrong track... (what one can pick from bunch of asterisks afterall).
This is the first time that approach is failing. But what can we do afterall, "!!!!!" thing is not a song.

Apparently I don't think... There is something we can do to fix this... As "!!!!!!" is not even a track.

What came in mind of Billie Eilish to break this much hardwork.
Now we have only two options... First one is, to remove the individual track search to fetch the links of music videos instead of music tracks & ruin other tracks... And second is just mark as "wontfix".

Or is there a way we can find if a particular track in that album are actually "music video" or "music track". (I'll see this later).

**Comment by mytja** [comment]
A guy discussed a similar problem here: https://github.com/sigma67/ytmusicapi/issues/84
@sigma67 said, that he will do the patch on this weekend!
Hope this helps!

**Comment by alexmercerind** [comment]
@mytja that's actually a different problem.

**Comment by mytja** [comment]
Oh......

**Comment by mytja** [comment]
You can just mark it as "wontfix", since this is very complicated

**Comment by alexmercerind** [comment]
@raitonoberu Happy Birthday!!! 🍰🍰🍰

**Comment by raitonoberu** [comment]
@alexmercerind Thank you bro <3

**Comment by mytja** [comment]
Happy birthday

**Comment by raitonoberu** [comment]
Hey guys, I think I fixed it. Check it out: [link](https://harmonoid-ru.herokuapp.com/albuminfo?album_id=MPREb_9gAdrkio5lF). Now it returns the right track_id: www.youtube.com/watch?v=XJBUWZsT38c
Changes are as simple as these lines:
https://github.com/raitonoberu/harmonoid-service/blob/d8936dc616cdee8035ee55acb563d372074c2d47/harmonoidservice/browsing.py#L225-L228
If search result is wrong, it returns the original videoId.
I also made the code more readeable (no more lists) and fixed several deploying issues.

**Important!** I changed the content of /artisttracks endpoint. Now it returns *{"tracks": ... }* instead of *{"albums": ... }*. If it was not a typo, change it back.

Thanks!

**Comment by alexmercerind** [comment]
👋 @raitonoberu!

Great! Amazing work.
Yup... It was a typo 😅. It should be "tracks". I didn't notice it.

Thanks for your great contribution.
